name: Test Firebase Emulators on Windows PowerShell

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-powershell-comma:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Firebase CLI
        # run: npm install -g firebase-tools
        run: |
          git clone https://github.com/firebase/firebase-tools.git -b aalej_handle-powershell-commas
          cd firebase-tools
          npm install
          npm run build
          npm link

      - name: Run Firebase Emulators
        shell: pwsh
        run: |
          firebase emulators:start --only auth,firestore,hosting --project demo-project
